### ISSUE TITLE
`jison` and `browserify` are global dependencies.

### ISSUE THREAD

**Issue by gburtini** [dimagi/js-xpath#13]
It looks like `node-qunit-phantomjs` and `jshint` are global devDependencies too. This should be documented somewhere, as the `npm run build` instructions fail somewhat ambiguously if `browserify` isn't installed.

**Comment by emord** [comment]
@gburtini thanks for finding this. I've added #15 to fix this. They are not global dependencies as `npm run build` is run with the packages installed with package.json
