### ISSUE TITLE
`main.js` is misleading

### ISSUE THREAD

**Issue by gburtini** [dimagi/js-xpath#14]
The entry point is actually `xpath.js` right now according to `package.json`. Perhaps rename `main.js` or move to a tools, src, or dist subdirectory.

**Comment by emord** [comment]
@gburtini that makes sense. I'm happy to review any PRs that make this more understandable by either updating documentation or changing the directory structure

**Comment by gburtini** [comment]
I'll get this done shortly.

**Comment by emord** [comment]
Thanks for the help with this @gburtini
